application: robot-robot
version: 1
runtime: python
api_version: 1
default_expiration: "7d"

handlers:
- url: /_wave/.*
  script: robot_robot.py
- url: /assets
  static_dir: assets
- url: /.*
  script: export.py